// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon May 13 01:27:31 2024

analyze analyze_inst
(
	.irq_frame(irq_frame_sig) ,	// input  irq_frame_sig
	.rst(rst_sig) ,	// input  rst_sig
	.result(result_sig) ,	// input [31:0] result_sig
	.flag(flag_sig) ,	// input  flag_sig
	.mode(mode_sig) ,	// output [3:0] mode_sig
	.f_big(f_big_sig) ,	// output [31:0] f_big_sig
	.f_small(f_small_sig) ,	// output [15:0] f_small_sig
	.A(A_sig) 	// output [7:0] A_sig
);

