// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Wed May 01 17:44:44 2024

ClkDiv ClkDiv_inst
(
	.clk(clk_sig) ,	// input  clk_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.phase_rst(phase_rst_sig) ,	// input  phase_rst_sig
	.clk_div(clk_div_sig) ,	// output  clk_div_sig
	.cnt(cnt_sig) 	// output [31:0] cnt_sig
);

defparam ClkDiv_inst.cnt_max = 'b00000000000000000000001111101000;
defparam ClkDiv_inst.cnt_threshold = 'b00000000000000000000000111110100;
