// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri May 24 17:53:15 2024

plus_signed plus_signed_inst
(
	.ci(ci_sig) ,	// input  ci_sig
	.num1(num1_sig) ,	// input [bit_big-1:0] num1_sig
	.num2(num2_sig) ,	// input [bit_small-1:0] num2_sig
	.cout_plus(cout_plus_sig) ,	// output  cout_plus_sig
	.cout_minor(cout_minor_sig) ,	// output  cout_minor_sig
	.result(result_sig) 	// output [bit_big-1:0] result_sig
);

defparam plus_signed_inst.bit_big = 8;
defparam plus_signed_inst.bit_small = 8;
