// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Fri May 24 14:34:59 2024

signed_multiple signed_multiple_inst
(
	.num1(num1_sig) ,	// input [bit_1-1:0] num1_sig
	.num2(num2_sig) ,	// input [bit_2-1:0] num2_sig
	.clk(clk_sig) ,	// input  clk_sig
	.rst(rst_sig) ,	// input  rst_sig
	.result(result_sig) 	// output [bit_1+bit_2-2:0] result_sig
);

defparam signed_multiple_inst.bit_1 = 14;
defparam signed_multiple_inst.bit_2 = 14;
