// Copyright (C) 2018  Intel Corporation. All rights reserved.
// Your use of Intel Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Intel Program License 
// Subscription Agreement, the Intel Quartus Prime License Agreement,
// the Intel FPGA IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Intel and sold by Intel or its authorized distributors.  Please
// refer to the applicable agreement for further details.


// Generated by Quartus Prime Version 18.1 (Build Build 625 09/12/2018)
// Created on Mon May 13 01:30:32 2024

uart_fromMCU uart_fromMCU_inst
(
	.RX(RX_sig) ,	// input  RX_sig
	.rst(rst_sig) ,	// input  rst_sig
	.clk(clk_sig) ,	// input  clk_sig
	.irq(irq_sig) ,	// output  irq_sig
	.flag(flag_sig) ,	// output  flag_sig
	.result(result_sig) 	// output [47:0] result_sig
);

defparam uart_fromMCU_inst.baud_rate = 'b00000000000000011100001000000000;
